// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8sWSVBaoD3J8guxuWHbXQhwte9Yl45lI',
    appId: '1:947572634270:web:ed4abdc9c6df144ae8018f',
    messagingSenderId: '947572634270',
    projectId: 'tanoshii-app1',
    authDomain: 'tanoshii-app1.firebaseapp.com',
    storageBucket: 'tanoshii-app1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg3dl9FpbuDY9yuUSWmj16Re5MgtgWUuY',
    appId: '1:947572634270:android:93501c1a2b8f99c3e8018f',
    messagingSenderId: '947572634270',
    projectId: 'tanoshii-app1',
    storageBucket: 'tanoshii-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUoz6UgDFxkAdHYyhwDxdRvPVfVNsXssA',
    appId: '1:947572634270:ios:030a0ab3d1065ee0e8018f',
    messagingSenderId: '947572634270',
    projectId: 'tanoshii-app1',
    storageBucket: 'tanoshii-app1.firebasestorage.app',
    iosBundleId: 'com.example.tanoshiiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUoz6UgDFxkAdHYyhwDxdRvPVfVNsXssA',
    appId: '1:947572634270:ios:030a0ab3d1065ee0e8018f',
    messagingSenderId: '947572634270',
    projectId: 'tanoshii-app1',
    storageBucket: 'tanoshii-app1.firebasestorage.app',
    iosBundleId: 'com.example.tanoshiiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8sWSVBaoD3J8guxuWHbXQhwte9Yl45lI',
    appId: '1:947572634270:web:03c445144a9a6e92e8018f',
    messagingSenderId: '947572634270',
    projectId: 'tanoshii-app1',
    authDomain: 'tanoshii-app1.firebaseapp.com',
    storageBucket: 'tanoshii-app1.firebasestorage.app',
  );

}